version: "3"

services:
  db:
    image: mariadb:latest
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp-docker-01
  
  wordpress:
    depends_on:
      - db
    image: wordpress:php8.1-fpm-alpine
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_PASSWORD}
    volumes: 
      - wordpress:/var/www/html
    networks:
      - wp-docker-01

  wpcli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    container_name: wordpress-cli
    user: 1000:1000
    environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress
        WORDPRESS_DB_NAME: wordpress
    command:
      - /bin/bash
      - -c
      - |
        sleep 10
        wp core install --url=${SITE_HOSTNAME} --title=${SITE_TITLE} --admin_user=${WP_ADMIN_USER} --admin_password=${WP_ADMIN_PASSWORD} --admin_email=${WP_ADMIN_EMAIL} --skip-email
    volumes:
      - wordpress:/var/www/html
    networks:
      - wp-docker-01
      
  nginx:
    depends_on:
      - wordpress
      - db
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - wp-docker-01
  
volumes:
  wordpress:
  db_data:
networks:
  wp-docker-01:
